#!/bin/sh
# postinst script for hadoop

set -e

case "$1" in
    configure)
	find /usr/lib/hadoop-0.20/sbin -name task-controller -exec chown root:mapred {} \;
	find /usr/lib/hadoop-0.20/sbin -name task-controller -exec chmod 4754 {} \;
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
